version: "3.8"
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
#  rabbitmq:
#    image: rabbitmq:3-alpine
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"